const [nombre, setNombre] = useState('')
const [tipo, setTipo] = useState('')
const [composicion, setComposicion] = useState('')
const [presentacion, setPresentacion] = useState('')
const [fechaV, setFechaV] = useState(null)
const [precioVenta, setPrecioVenta] = useState(0.0)
const [precioCompra, setPrecioCompra] = useState(0.0)
const [cantidad, setCantidad] = useState(0)